stages:
  - build
  - push

variables:
  DOCKER_DRIVER: overlay2
  IMAGE_FRONTEND: varshh21/neuro-link-frontend:latest
  IMAGE_BACKEND: varshh21/neuro-link-backend:latest

before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin

build-frontend:
  stage: build
  script:
    - cd frontend
    - npm install
    - docker build -t $IMAGE_FRONTEND .
  only:
    - main

build-backend:
  stage: build
  script:
    - cd backend
    - npm install
    - docker build -t $IMAGE_BACKEND .
  only:
    - main

push-frontend:
  stage: push
  script:
    - docker push $IMAGE_FRONTEND
  only:
    - main
  dependencies:
    - build-frontend

push-backend:
  stage: push
  script:
    - docker push $IMAGE_BACKEND
  only:
    - main
  dependencies:
    - build-backend
