image: docker:20.10.16

services:
  - docker:dind

stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - docker info

build_images:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE/frontend ./frontend
    - docker build -t $CI_REGISTRY_IMAGE/backend ./backend

deploy:
  stage: deploy
  script:
    - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE/frontend
    - docker push $CI_REGISTRY_IMAGE/backend
