image: python:3.9

stages:
  - build
  - test

before_script:
  - pip install -r requirements.txt

build:
  stage: build
  script:
    - echo "Build passed"

test:
  stage: test
  script:
    - python -m unittest discover tests
